### ISSUE TITLE
Scanners disconnect and loose service at random intervals

### ISSUE THREAD

**Issue by thecomet28** [Secure-Compliance-Solutions-LLC/OpenVAS-Docker#2]
I have a few remote scanners that we have deployed to different environments but they all operate on Ubuntu 20.04. Recently, we have been seeing many remote scanners that we have deployed disconnecting from the GVM11 control system. We can usually get it reconnected by restarting the docker image but it fails after a random time again. Can anyone help cause we are constantly having to restart it and scans are not running.

**Comment by pixelsquared** [comment]
Hi,

Sorry I didn't respond earlier. We are aware of this issue and I am trying to create a solution for this. It is a little tricky to debug because it does not happen predictably.

**Comment by thecomet28** [comment]
I think I may have found a solution. We set/added the TCPKeepAlive to no in the ssh config. So far we have had luck with it no longer disconnecting. I will let you know once it has been successful for a few weeks.

**Comment by oddbodperkins** [comment]
Also facing the same issues, I've tried restarting both the remote Openvas containers, as well as the local GVM20 container to no avail. I've also added a brand new remote scanner but it fails to connect; peculiar since I had added about 10 remote scanners at different remote locations when I first utilized this project. Those initial 10 scanners also cannot connect back to the main gvm20 container

**Comment by Dexus** [comment]
maybe this is related to https://github.com/greenbone/openvas-scanner/pull/832
